name: ui_vision_lab
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pyqt
  - qt-main
  - opencv
  - pyyaml
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - pip
  - pip:
      - easyocr
      - mss
